Various JavaScript Goodies: interesting snippets collected.

* [[./displayhtml][displayHTML]]

Very simple utility to display syntax-highlighted HTML while preserving the HTML
structure, useful for demonstrating DOM selection.

** Origin

http://codepen.io/GeekTrainer/pen/EjMxKL

* [[./htmlEncode][htmlEncode/htmlDecode]]
This might be too simple to be a goodie on its own. But answers at [[Origin]]
suggest it the other way. Key notes:

- Still not a built-in API in HTML.
- 'replace' is the widely used method (as it has no extra dependencies)
- =underscore= has built-in support.

** Origin
[[http://stackoverflow.com/questions/1219860/html-encoding-in-javascript-jquery][HTML-encoding in JavaScript/jQuery - Stack Overflow]]

* miniEventEmitter

An home-brew =EventEmitter= serves as an intermediate step for naturally
requiring a full framework like =Backbone=. This serves as an minimalist event
example. A mocha test file is also included.

** Origin
First used in my [[https://github.com/carltonf/win-allowed-time/commit/91b2fd3d51e6073cf12d0f0f2e75fe49f1f65e80][Move to event-driven arch Part2 · carltonf/win-allowed-time@91b2fd3]].

Later on, it's replaced by node's own =EventEmitter=, which can be browerified
for client-side use.
